spring:
  application:
    name: fms-api
  datasource:
    url: jdbc:postgresql://localhost:5432/fleet_management
    username: jania
    password: jania
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: "e138f3c864cdf4583d99ad6c91e4f790e7d671d0b3e52c6482c835beeea6a98c"
  expiration: 86400000