spring:
  application:
    name: fms-api
  datasource:
    url: jdbc:postgresql://localhost:5432/fleet_management
    username: jania
    password: jania
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
